# Generated by Django 3.1.4 on 2021-09-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='header/img/', verbose_name='Логотип (303х90)')),
                ('address_ru', models.CharField(max_length=200, verbose_name='Адрес на русском')),
                ('address_uz', models.CharField(max_length=200, verbose_name='Адрес на на узбекском')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.CharField(max_length=200, verbose_name='Telegram')),
                ('instagram', models.CharField(max_length=200, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=200, verbose_name='Facebook')),
                ('youtube_1', models.CharField(max_length=200, verbose_name='Youtube 1')),
                ('youtube_2', models.CharField(max_length=200, verbose_name='Youtube 2')),
            ],
            options={
                'verbose_name': 'Шапка сайта',
                'verbose_name_plural': 'Шапка сайта',
            },
        ),
    ]
