# Generated by Django 3.1.4 on 2021-09-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=200, verbose_name='Telegram')),
                ('instagram', models.CharField(max_length=200, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=200, verbose_name='Facebook')),
                ('youtube_1', models.CharField(max_length=200, verbose_name='Youtube 1')),
                ('youtube_2', models.CharField(max_length=200, verbose_name='Youtube 2')),
                ('worktime_ru', models.CharField(max_length=200, verbose_name='Режим работы на русском')),
                ('worktime_uz', models.CharField(max_length=200, verbose_name='Режим работы на узбекском')),
                ('address_ru', models.CharField(max_length=200, verbose_name='Адрес на русском')),
                ('address_uz', models.CharField(max_length=200, verbose_name='Адрес на на узбекском')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Подвал сайта',
                'verbose_name_plural': 'Подвал сайта',
            },
        ),
    ]
