# Generated by Django 3.1.4 on 2021-09-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок на русском')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Заголовок на узбекском')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_uz', models.TextField(verbose_name='Описание на узбекском')),
            ],
        ),
    ]
