# Generated by Django 3.1.4 on 2021-09-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_firstblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_block_title_ru', models.CharField(max_length=200, verbose_name='Заголовок первого блока на русском')),
                ('first_block_title_uz', models.CharField(max_length=200, verbose_name='Заголовок первого блока на узбекском')),
                ('first_block_description_ru', models.TextField(verbose_name='Описание первого блока на русском')),
                ('first_block_description_uz', models.TextField(verbose_name='Описание первого блока на узбекском')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.DeleteModel(
            name='FirstBlock',
        ),
    ]
