# Generated by Django 3.1.4 on 2021-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210903_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Название на узбекском')),
                ('img', models.ImageField(upload_to='mainpage/steps/', verbose_name='Изображение (115х69)')),
            ],
            options={
                'verbose_name': 'Этап работ',
                'verbose_name_plural': 'Этапы работ',
            },
        ),
    ]
