# Generated by Django 3.1.4 on 2021-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_worksteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='work_steps',
            field=models.ManyToManyField(to='mainapp.WorkSteps', verbose_name='Блок "Как мы работаем"'),
        ),
    ]
