# Generated by Django 3.1.4 on 2021-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_mainpage_work_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='about_img',
            field=models.ImageField(default=123, upload_to='mainpage/', verbose_name='О компании Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_par_1',
            field=models.TextField(default=123, verbose_name='О компании Первый абзац'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_par_2',
            field=models.TextField(default=123, verbose_name='О компании Второй абзац'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='client',
            field=models.IntegerField(default=123, verbose_name='Счетчик клиентов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='sold',
            field=models.IntegerField(default=123, verbose_name='Счетчик проданных товаров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='success',
            field=models.IntegerField(default=123, verbose_name='Счетчик успешных заказов'),
            preserve_default=False,
        ),
    ]
