# Generated by Django 3.1.4 on 2021-09-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.ImageField(upload_to='mainpage/partners/', verbose_name='Изображение (244х133)')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='about_par_1',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='about_par_2',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_par_1_ru',
            field=models.TextField(default=123, verbose_name='О компании Первый абзац на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_par_1_uz',
            field=models.TextField(default=123, verbose_name='О компании Первый абзац на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_par_2_ru',
            field=models.TextField(default=123, verbose_name='О компании Второй абзац на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='about_par_2_uz',
            field=models.TextField(default=123, verbose_name='О компании Второй абзац на узбекском'),
            preserve_default=False,
        ),
    ]
