# Generated by Django 3.1.4 on 2021-09-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210905_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='work_steps',
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_img',
            field=models.ImageField(upload_to='mainpage/', verbose_name='О компании Изображение (464х411)'),
        ),
    ]
