# Generated by Django 3.1.4 on 2021-09-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210907_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_title_1_ru', models.CharField(max_length=200, verbose_name='Название телефона 1 на русском')),
                ('phone_title_1_uz', models.CharField(max_length=200, verbose_name='Название телефона 1 на узбекском')),
                ('phone_1', models.CharField(max_length=200, verbose_name='Телефон 1')),
                ('phone_title_2_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название телефона 2 на русском')),
                ('phone_title_2_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название телефона 2 на узбекском')),
                ('phone_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон 2')),
                ('phone_title_3_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название телефона 3 на русском')),
                ('phone_title_3_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название телефона 3 на узбекском')),
                ('phone_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон 3')),
                ('phone_title_4_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название телефона 4 на русском')),
                ('phone_title_4_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название телефона 4 на узбекском')),
                ('phone_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон 4')),
                ('phone_title_5_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название телефона 5 на русском')),
                ('phone_title_5_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название телефона 5 на узбекском')),
                ('phone_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон 5')),
                ('mail_title_1_ru', models.CharField(max_length=200, verbose_name='Название почты 1 на русском')),
                ('mail_title_1_uz', models.CharField(max_length=200, verbose_name='Название почты 1 на узбекском')),
                ('mail_1', models.CharField(max_length=200, verbose_name='Почта 1')),
                ('mail_title_2_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название почты 2 на русском')),
                ('mail_title_2_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название почты 2 на узбекском')),
                ('mail_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта 2')),
                ('mail_title_3_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название почты 3 на русском')),
                ('mail_title_3_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название почты 3 на узбекском')),
                ('mail_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта 3')),
                ('mail_title_4_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название почты 4 на русском')),
                ('mail_title_4_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название почты 4 на узбекском')),
                ('mail_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта 4')),
                ('mail_title_5_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название почты 5 на русском')),
                ('mail_title_5_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название почты 5 на узбекском')),
                ('mail_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта 5')),
                ('address_title_1_ru', models.CharField(max_length=200, verbose_name='Название адреса 1 на русском')),
                ('address_title_1_uz', models.CharField(max_length=200, verbose_name='Название адреса 1 на узбекском')),
                ('address_1', models.CharField(max_length=200, verbose_name='Адрес 1')),
                ('address_title_2_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название адреса 2 на русском')),
                ('address_title_2_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название адреса 2 на узбекском')),
                ('address_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 2')),
                ('address_title_3_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название адреса 3 на русском')),
                ('address_title_3_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название адреса 3 на узбекском')),
                ('address_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 3')),
                ('address_title_4_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название адреса 4 на русском')),
                ('address_title_4_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название адреса 4 на узбекском')),
                ('address_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 4')),
                ('address_title_5_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название адреса 5 на русском')),
                ('address_title_5_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название адреса 5 на узбекском')),
                ('address_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 5')),
                ('callback_text', models.TextField(verbose_name='Текст обратной связи')),
            ],
            options={
                'verbose_name': 'Страница "Контакты"',
                'verbose_name_plural': 'Страница "Контакты"',
            },
        ),
    ]
