# Generated by Django 3.1.4 on 2021-09-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='address_3',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='address_4',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='address_5',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_1_ru',
            field=models.CharField(default=123, max_length=200, verbose_name='Адрес 1 на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_1_uz',
            field=models.CharField(default=123, max_length=200, verbose_name='Адрес 1 на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_2_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 2 на русском'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_2_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 2 на узбекском'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_3_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 3 на русском'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_3_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 3 на узбекском'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_4_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 4 на русском'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_4_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 4 на узбекском'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_5_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 5 на русском'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address_5_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес 5 на узбекском'),
        ),
    ]
