# Generated by Django 3.1.4 on 2021-09-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210913_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='callback_text',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='callback_text_ru',
            field=models.TextField(default=123, verbose_name='Текст обратной связи на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='callback_text_uz',
            field=models.TextField(default=123, verbose_name='Текст обратной связи на узбекском'),
            preserve_default=False,
        ),
    ]
