# Generated by Django 3.1.4 on 2021-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210913_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentTermPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits_ru', models.TextField(verbose_name='Преимущества аренды на русском')),
                ('benefits_uz', models.TextField(verbose_name='Преимущества аренды на узбекском')),
                ('suggestions_ru', models.TextField(verbose_name='Наши предложения на русском')),
                ('suggestions_uz', models.TextField(verbose_name='Наши предложения на узбекском')),
            ],
            options={
                'verbose_name': 'Страница "Условия аренды"',
                'verbose_name_plural': 'Страница "Условия аренды"',
            },
        ),
    ]
