# Generated by Django 3.1.4 on 2021-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_renttermpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Страница "Доставка"',
                'verbose_name_plural': 'Страница "Доставка"',
            },
        ),
    ]
