# Generated by Django 3.1.4 on 2021-09-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_deliverypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypage',
            name='text',
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='text_ru',
            field=models.TextField(default=123, verbose_name='Текст страницы на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='text_uz',
            field=models.TextField(default=123, verbose_name='Текст страницы на узбекском'),
            preserve_default=False,
        ),
    ]
