# Generated by Django 3.1.4 on 2021-09-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210914_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Название на узбекском')),
                ('desc_1_ru', models.TextField(verbose_name='Краткое описание на русском')),
                ('desc_1_uz', models.TextField(verbose_name='Краткое описание на узбекском')),
                ('object_name_1_ru', models.CharField(max_length=200, verbose_name='Название первого объекта на русском')),
                ('object_name_1_uz', models.CharField(max_length=200, verbose_name='Название первого объекта на узбекском')),
                ('object_desc_1_ru', models.CharField(max_length=200, verbose_name='Описание первого обекта на русском')),
                ('object_desc_1_uz', models.CharField(max_length=200, verbose_name='Описание первого обекта на узбекском')),
                ('object_img_1', models.ImageField(upload_to='services/', verbose_name='Изображение первого объекта')),
                ('object_name_2_ru', models.CharField(max_length=200, verbose_name='Название второго объекта на русском')),
                ('object_name_2_uz', models.CharField(max_length=200, verbose_name='Название второго объекта на узбекском')),
                ('object_desc_2_ru', models.CharField(max_length=200, verbose_name='Описание второго обекта на русском')),
                ('object_desc_2_uz', models.CharField(max_length=200, verbose_name='Описание второго обекта на узбекском')),
                ('object_img_2', models.ImageField(upload_to='services/', verbose_name='Изображение второго объекта')),
                ('object_name_3_ru', models.CharField(max_length=200, verbose_name='Название третьего объекта на русском')),
                ('object_name_3_uz', models.CharField(max_length=200, verbose_name='Название третьего объекта на узбекском')),
                ('object_desc_3_ru', models.CharField(max_length=200, verbose_name='Описание третьего обекта на русском')),
                ('object_desc_3_uz', models.CharField(max_length=200, verbose_name='Описание третьего обекта на узбекском')),
                ('object_img_3', models.ImageField(upload_to='services/', verbose_name='Изображение третьего объекта')),
                ('object_name_4_ru', models.CharField(max_length=200, verbose_name='Название четвертого объекта на русском')),
                ('object_name_4_uz', models.CharField(max_length=200, verbose_name='Название четвертого объекта на узбекском')),
                ('object_desc_4_ru', models.CharField(max_length=200, verbose_name='Описание четвертого обекта на русском')),
                ('object_desc_4_uz', models.CharField(max_length=200, verbose_name='Описание четвертого обекта на узбекском')),
                ('object_img_4', models.ImageField(upload_to='services/', verbose_name='Изображение четвертого объекта')),
                ('desc_2_ru', models.TextField(verbose_name='Полное описание на русском')),
                ('desc_2_uz', models.TextField(verbose_name='Полное описание на узбекском')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
