# Generated by Django 3.1.4 on 2021-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='object_img_1',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение первого объекта (232х232)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='object_img_2',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение второго объекта (232х232)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='object_img_3',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение третьего объекта (232х232)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='object_img_4',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение четвертого объекта (232х232)'),
        ),
    ]
