# Generated by Django 3.1.4 on 2021-09-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210915_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1_ru', models.TextField(verbose_name='Краткое описание на русском')),
                ('text_1_uz', models.TextField(verbose_name='Краткое описание на узбекском')),
                ('text_2_ru', models.TextField(verbose_name='Полное описание на русском')),
                ('text_2_uz', models.TextField(verbose_name='Полное описание на узбекском')),
                ('year', models.IntegerField(verbose_name='Лет на рынке')),
                ('order', models.IntegerField(verbose_name='Количество заказов')),
                ('delivery', models.IntegerField(verbose_name='Количество доставок')),
                ('repeated', models.IntegerField(verbose_name='Процент повторных обращений')),
            ],
            options={
                'verbose_name': 'Страница "О компании"',
                'verbose_name_plural': 'Страница "О компании"',
            },
        ),
    ]
