# Generated by Django 3.1.4 on 2021-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_header_top_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='top_category',
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_1_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Первая топ-категория на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_1_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Первая топ-категория на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_2_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Вторая топ-категория на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_2_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Вторая топ-категория на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_3_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Третья топ-категория на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_3_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Третья топ-категория на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_4_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Четвертая топ-категория на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_4_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Четвертая топ-категория на узбекском'),
            preserve_default=False,
        ),
    ]
