# Generated by Django 3.1.4 on 2021-11-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20211101_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='top_category_1_slug',
            field=models.SlugField(default=1, verbose_name='URL Первой топ-категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_2_slug',
            field=models.SlugField(default=1, verbose_name='URL Второй топ-категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_3_slug',
            field=models.SlugField(default=1, verbose_name='URL Третьей топ-категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='top_category_4_slug',
            field=models.SlugField(default=1, verbose_name='URL Четвертой топ-категории'),
            preserve_default=False,
        ),
    ]
