# Generated by Django 3.1.4 on 2021-11-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20211101_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='top_category_1_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_1_slug',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_1_uz',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_2_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_2_slug',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_2_uz',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_3_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_3_slug',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_3_uz',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_4_ru',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_4_slug',
        ),
        migrations.RemoveField(
            model_name='header',
            name='top_category_4_uz',
        ),
    ]
