# Generated by Django 3.1.4 on 2022-02-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20220216_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_description_ru',
            field=models.TextField(default=123, verbose_name='Meta Description на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_description_uz',
            field=models.TextField(default=123, verbose_name='Meta Description на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_keywords_ru',
            field=models.CharField(default=123, max_length=200, verbose_name='Meta Keywords на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_keywords_uz',
            field=models.CharField(default=123, max_length=200, verbose_name='Meta Keywords на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_title_ru',
            field=models.CharField(default=123, max_length=200, verbose_name='Meta Title на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_title_uz',
            field=models.CharField(default=123, max_length=200, verbose_name='Meta Title на узбекском'),
            preserve_default=False,
        ),
    ]
