# Generated by Django 3.1.4 on 2022-02-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20220218_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='youtube_1',
            new_name='youtube',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='youtube_1',
            new_name='youtube',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube_2',
        ),
        migrations.RemoveField(
            model_name='header',
            name='youtube_2',
        ),
    ]
