# Generated by Django 3.1.4 on 2022-02-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20220219_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='meta_description_ru',
            field=models.TextField(default=1, verbose_name='Meta Description на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_description_uz',
            field=models.TextField(default=1, verbose_name='Meta Description на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_keywords_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Keywords на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_keywords_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Keywords на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Title на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactpage',
            name='meta_title_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Title на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_description_ru',
            field=models.TextField(default=1, verbose_name='Meta Description на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_description_uz',
            field=models.TextField(default=1, verbose_name='Meta Description на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_keywords_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Keywords на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_keywords_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Keywords на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_title_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Title на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypage',
            name='meta_title_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Title на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renttermpage',
            name='meta_description_ru',
            field=models.TextField(default=1, verbose_name='Meta Description на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renttermpage',
            name='meta_description_uz',
            field=models.TextField(default=1, verbose_name='Meta Description на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renttermpage',
            name='meta_keywords_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Keywords на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renttermpage',
            name='meta_keywords_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Keywords на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renttermpage',
            name='meta_title_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Title на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renttermpage',
            name='meta_title_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Meta Title на узбекском'),
            preserve_default=False,
        ),
    ]
