# Generated by Django 3.1.4 on 2021-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211101_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_1',
            field=models.ImageField(default=1, upload_to='product_img/', verbose_name='Основное изображение товара (960х1280)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/', verbose_name='Дополнительное изображение товара (960х1280)'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/', verbose_name='Дополнительное изображение товара (960х1280)'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/', verbose_name='Дополнительное изображение товара (960х1280)'),
        ),
        migrations.AddField(
            model_name='product',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to='product_img/', verbose_name='Дополнительное изображение товара (960х1280)'),
        ),
    ]
