# Generated by Django 3.1.4 on 2021-11-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211102_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rent',
            field=models.BooleanField(default=1, verbose_name='Аренда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.BooleanField(default=1, verbose_name='Продажа'),
            preserve_default=False,
        ),
    ]
