# Generated by Django 3.1.4 on 2021-11-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211102_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='file_1',
            field=models.FileField(default=1, upload_to='product_files/', verbose_name='Файл 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='product_files/', verbose_name='Файл 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='product_files/', verbose_name='Файл 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='product_files/', verbose_name='Файл 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_1',
            field=models.CharField(default=1, max_length=200, verbose_name='Характеристика 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='spec_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Характеристика 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Характеристика 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Характеристика 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Характеристика 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Характеристика 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='val_1',
            field=models.CharField(default=1, max_length=200, verbose_name='Значение 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='val_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='val_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='val_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='val_5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='val_6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение 6'),
        ),
    ]
