# Generated by Django 3.1.4 on 2021-11-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211103_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Название на узбекском')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория аренды',
                'verbose_name_plural': 'Категории аренды',
            },
        ),
        migrations.CreateModel(
            name='RentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Название на узбекском')),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Арендуемый товар',
                'verbose_name_plural': 'Арендуемые товары',
            },
        ),
    ]
