# Generated by Django 3.1.4 on 2021-11-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rentproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.rentcategory', verbose_name='Категория'),
        ),
    ]
