# Generated by Django 3.1.4 on 2021-11-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211108_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproduct',
            name='img_1',
            field=models.ImageField(default=1, upload_to='product_img/', verbose_name='Основное изображение товара (960х1280)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='term',
            field=models.IntegerField(default=1, verbose_name='Срок(в днях)'),
            preserve_default=False,
        ),
    ]
