# Generated by Django 3.1.4 on 2021-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211108_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproduct',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='rent_product_img/', verbose_name='Дополнительное изображение товара (960х1280)'),
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='rent_product_img/', verbose_name='Дополнительное изображение товара (960х1280)'),
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='rent_product_img/', verbose_name='Дополнительное изображение товара (960х1280)'),
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to='rent_product_img/', verbose_name='Дополнительное изображение товара (960х1280)'),
        ),
        migrations.AlterField(
            model_name='rentproduct',
            name='img_1',
            field=models.ImageField(upload_to='rent_product_img/', verbose_name='Основное изображение товара (960х1280)'),
        ),
    ]
