# Generated by Django 3.1.4 on 2021-11-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211108_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproduct',
            name='country_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Страна производителя (на русском)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='country_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Страна производителя (на узбекском)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='delivery',
            field=models.BooleanField(default=1, verbose_name='Возможность доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='height',
            field=models.IntegerField(default=1, verbose_name='Высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='length',
            field=models.IntegerField(default=1, verbose_name='Длинна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='material_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Материал (на русском)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='material_uz',
            field=models.CharField(default=1, max_length=200, verbose_name='Материал (на узбекском)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='max_height',
            field=models.IntegerField(default=1, verbose_name='Максимальная высота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='max_load',
            field=models.IntegerField(default=1, verbose_name='Максимальная нагрузка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество в комплекте'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='self_pickup',
            field=models.BooleanField(default=1, verbose_name='Возможность самовывоза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='width',
            field=models.IntegerField(default=1, verbose_name='Ширина'),
            preserve_default=False,
        ),
    ]
