# Generated by Django 3.1.4 on 2021-11-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20211108_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_1_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название файла 1 на русском'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_1_name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название файла 1 на узбекском'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_2_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название файла 2 на русском'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_2_name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название файла 2 на узбекском'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_3_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название файла 3 на русском'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_3_name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название файла 3 на узбекском'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_4_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название файла 4 на русском'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_4_name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название файла 4 на узбекском'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='product_files/', verbose_name='Файл 1'),
        ),
    ]
